services:
  - type: redis
    name: task-system-redis
    plan: free

  - type: web
    name: task-system-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: task-system-redis
          property: hostname

  - type: worker
    name: task-system-worker1
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: task-system-redis
          property: hostname

  - type: worker
    name: task-system-worker2
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: task-system-redis
          property: hostname

  - type: worker
    name: task-system-worker3
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: task-system-redis
          property: hostname
