services:
  - type: redis
    name: task-system-redis
    plan: free
    ipAllowList: []

  - type: web
    name: task-system-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REDIS_HOST
        fromService:
          type: redis
          name: task-system-redis
          property: host
      - key: REDIS_PORT
        value: 6379
